#!/bin/bash

npx playwright install chromium

CHROME_DIR=$(find /root/.cache/ms-playwright/ -maxdepth 1 -type d -name 'chromium-*' | head -1)
CHROME_DIR=$CHROME_DIR/chrome-linux
CHROME_PATH=$CHROME_DIR/chrome

if [ ! -f "$CHROME_PATH" ]; then
  echo 'Chrome is not found'
  exit 1
fi

BASE_PATH="$CHROME_PATH-base"
if [ -e "$BASE_PATH" ]; then
  exit
fi
mv "$CHROME_PATH" "$BASE_PATH"

FLUXBOX_MENU=/root/.fluxbox/menu
if [ ! -f $FLUXBOX_MENU ]; then
  mkdir -p /root/.fluxbox
  echo -e '[begin] (fluxbox)\n[include] (/etc/X11/fluxbox/fluxbox-menu)\n[end]' > $FLUXBOX_MENU
fi
CHROME_LOGO=$(find "$CHROME_DIR" -maxdepth 1 -name 'product_logo_*' | head -1)
if ! cat $FLUXBOX_MENU | grep "$CHROME_LOGO" > /dev/null; then
  sed -e "/(fluxbox)/a [submenu] (Playwright) {}\n[exec] (Google Chrome) \{${CHROME_PATH}\} <${CHROME_LOGO}>\n[end]" -i $FLUXBOX_MENU
fi

cat > "$CHROME_PATH" <<_EOF
#!/bin/bash

# umask 002 ensures default permissions of files are 664 (rw-rw-r--) and directories are 775 (rwxrwxr-x).
umask 002

# Note: exec -a below is a bashism.
exec -a "\$0" "$BASE_PATH" \
  --allow-running-insecure-content \
  --disable-background-networking \
  --disable-client-side-phishing-detection \
  --disable-default-apps \
  --disable-hang-monitor \
  --disable-sync \
  --ignore-certificate-errors \
  --ignore-urlfetcher-cert-requests \
  --no-first-run \
  --no-sandbox \
  "\$@"
_EOF
chmod +x "$CHROME_PATH"
