name: Docker build image Playwright for Chrome

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
  push:
    paths:
      - '.github/workflows/build-playwright-chrome.yml'
      - 'chrome/**'
      - 'playwright/**'
      - 's6/**'
      - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest playwright version
        run: |
          echo "playwright=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/microsoft/playwright.git '*.*.*' | tail -1 | cut -d/ -f3)" >> $GITHUB_ENV
        shell: bash
      - uses: actions/cache@v2
        id: cache
        if: github.ref_name == 'main' && github.event_name == 'schedule'
        with:
          path: playwright-chrome
          key: ${{ runner.os }}-${{ env.playwright }}
          lookup-only: true
      - name: Set variables
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "branch=docker-playwright" >> $GITHUB_ENV
            echo "expires=10w" >> $GITHUB_ENV
          else
            echo "branch=test-docker-playwright" >> $GITHUB_ENV
            echo "expires=3d" >> $GITHUB_ENV
            echo "playwright=${{ env.playwright }}-${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: Checkout
        uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Login to Quay.io
        uses: docker/login-action@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          context: .
          file: ./chrome/Dockerfile
          labels: quay.expires-after=${{ env.expires }}
          push: true
          tags: quay.io/putara/${{ env.branch }}/chrome:${{ env.playwright }}

  test:
    runs-on: ubuntu-latest
    container:
      image: docker:20.10-git
    needs:
      - build
    steps:
      - name: Get latest playwright version
        run: |
          echo "playwright=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/microsoft/playwright.git '*.*.*' | tail -1 | cut -d/ -f3)" >> $GITHUB_ENV
      - uses: actions/cache@v2
        id: cache
        if: github.ref_name == 'main' && github.event_name == 'schedule'
        with:
          path: playwright-chrome
          key: ${{ runner.os }}-${{ env.playwright }}
          lookup-only: true
      - name: Set variables
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "branch=docker-playwright" >> $GITHUB_ENV
          else
            echo "branch=test-docker-playwright" >> $GITHUB_ENV
            echo "playwright=${{ env.playwright }}-${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: Checkout
        uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Build test
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker build -f tests/Dockerfile -t test . --build-arg BRANCH=${{ env.branch }} --build-arg APP=chrome --build-arg TAG=${{ env.playwright }}
      - name: Run test
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker start -a $(docker container create -e TEST_RUNNER=chrome test)
      - name: Login to Quay.io
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "${{ secrets.QUAY_PASSWORD }}" | docker login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin
      - name: Tag the latest
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker pull quay.io/putara/${{ env.branch }}/chrome:${{ env.playwright }}
          docker tag quay.io/putara/${{ env.branch }}/chrome:${{ env.playwright }} quay.io/putara/${{ env.branch }}/chrome:latest
          docker push quay.io/putara/${{ env.branch }}/chrome:latest
